window.catalogProducts = [
  {
    "id": "d1",
    "source": "digitalpc",
    "name": "LENOVO IDEAPAD SLIM 3 Intel Core I3-N305 8gb RAM 128gb SSD 15.6” W11 $ 435.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 435.0,
    "image": "imagenes/01-lenovo-ideapad-slim-3-intel-core-i3-n305-8gb-ram-128gb-ssd-1.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2025/08/FOTOS-WEB-12.jpg",
    "url": "https://digitalpcecuador.com/producto/lenovo-ideapad-slim-3-intel-core-i3-n305-8gb-ram-128gb-ssd-15-6-w11/",
    "badge": "#1 más económico"
  },
  {
    "id": "d2",
    "source": "digitalpc",
    "name": "ASUS VIVOBOOK 14 X1404VA Intel Core I3-1315U 8gb RAM 128gb SSD 14″ W11 $ 455.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 455.0,
    "image": "imagenes/02-asus-vivobook-14-x1404va-intel-core-i3-1315u-8gb-ram-128gb-s.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2025/07/descarga-7.png",
    "url": "https://digitalpcecuador.com/producto/asus-vivobook-14-x1404va-intel-core-i3-1315u-8gb-ram-128gb-ssd-14-w11-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "d3",
    "source": "digitalpc",
    "name": "HP 15-FD0130WM Intel Core I3-N305 8gb RAM 256gb SSD 15.6″ W11 $ 499.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 499.0,
    "image": "imagenes/03-hp-15-fd0130wm-intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/09/HP1-3.png",
    "url": "https://digitalpcecuador.com/producto/hp-15-fd0130wm-intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "d4",
    "source": "digitalpc",
    "name": "HP 15-FD0133WM Intel Core I3-N305 8gb RAM 256gb SSD 15.6″ W11 $ 499.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 499.0,
    "image": "imagenes/04-hp-15-fd0133wm-intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/09/HP1-3.png",
    "url": "https://digitalpcecuador.com/producto/hp-15-fd0133wm-intel-core-i3-n305-8gb-ram-256gb-ssd-15-6-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "d5",
    "source": "digitalpc",
    "name": "ASUS VIVOBOOK 14 X1404VAP Intel Core 5-120U 8gb RAM 256gb SSD 14″ W11 $ 575.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 575.0,
    "image": "imagenes/05-asus-vivobook-14-x1404vap-intel-core-5-120u-8gb-ram-256gb-ss.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2025/08/descarga-4-2.png",
    "url": "https://digitalpcecuador.com/producto/asus-vivobook-14-x1404vap-intel-core-5-120u-8gb-ram-256gb-ssd-14-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "d6",
    "source": "digitalpc",
    "name": "HP 15-fc0256la AMD Ryzen 5-7520U 16gb RAM 512gb SSD 15.6″ $ 655.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 655.0,
    "image": "imagenes/06-hp-15-fc0256la-amd-ryzen-5-7520u-16gb-ram-512gb-ssd-15-6-655.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2025/09/FOTOS-WEB.jpg",
    "url": "https://digitalpcecuador.com/producto/hp-15-fc0256la-amd-ryzen-5-7520u-16gb-ram-512gb-ssd-15-6/",
    "badge": "Precio bajo"
  },
  {
    "id": "d7",
    "source": "digitalpc",
    "name": "LENOVO IDEAPAD 1 Intel Core I5-1335U 16gb RAM 256gb SSD 15.6” W11 $ 675.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 675.0,
    "image": "imagenes/07-lenovo-ideapad-1-intel-core-i5-1335u-16gb-ram-256gb-ssd-15-6.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/06/FOTOS-WEB-27.jpg",
    "url": "https://digitalpcecuador.com/producto/lenovo-ideapad-1-intel-core-i5-1335u-16gb-ram-256gb-ssd-15-6-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "d8",
    "source": "digitalpc",
    "name": "ASUS VIVOBOOK GO 15 E1504FA RYZEN 5-40 16GB 512SSD 15,6´´ FHD $ 675.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 675.0,
    "image": "imagenes/08-asus-vivobook-go-15-e1504fa-ryzen-5-40-16gb-512ssd-15-6-fhd-.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/07/PORTADA-2.png",
    "url": "https://digitalpcecuador.com/producto/asus-vivobook-go-15-e1504fa-ryzen-5-4016gb512ssd156fhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "d9",
    "source": "digitalpc",
    "name": "HP 250R G10 Intel Core 5-120U 16gb RAM 512gb SSD 15.6″ $ 675.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 675.0,
    "image": "imagenes/09-hp-250r-g10-intel-core-5-120u-16gb-ram-512gb-ssd-15-6-675-00.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2025/07/FOTOS-WEB-13.jpg",
    "url": "https://digitalpcecuador.com/producto/hp-250r-g10-intel-core-i5-120u-16gb-ram-512gb-ssd-15-6/",
    "badge": "Precio bajo"
  },
  {
    "id": "d10",
    "source": "digitalpc",
    "name": "HP OMNIBOOK 3 16 AMD Ryzen 5 40 APU 16gb RAM 256g SSD 16” 2K IPS TOUCH W11 $ 695.00",
    "specs": "Equipo tecnológico · Rendimiento confiable · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 695.0,
    "image": "imagenes/10-hp-omnibook-3-16-amd-ryzen-5-40-apu-16gb-ram-256g-ssd-16-2k-.jpg",
    "image_remote": "https://digitalpcecuador.com/wp-content/uploads/2026/06/735362.jpg",
    "url": "https://digitalpcecuador.com/producto/hp-omnibook-3-16-amd-ryzen-5-40-apu-16gb-ram-256g-ssd-16-2k-ips-touch-w11/",
    "badge": "Precio bajo"
  },
  {
    "id": "m1",
    "source": "mundotek",
    "name": "Infinix SMART 6 HD Ram 2GB- 32GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 69.0,
    "image": "imagenes/11-infinix-smart-6-hd-ram-2gb--32gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/infinix-smart-6-hd-azul-600x600.webp",
    "url": "https://mundotek.com.ec/producto/infinix-smart-6-hd-ram-2gb-32gb/",
    "badge": "#1 más económico"
  },
  {
    "id": "m2",
    "source": "mundotek",
    "name": "ZTE Blade A35e RAM 4+2GB/64GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 89.0,
    "image": "imagenes/12-zte-blade-a35e-ram-4-2gb-64gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/zte_blade_a35e-300x300.webp",
    "url": "https://mundotek.com.ec/producto/zte-blade-a35e-ram-42gb-64gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m3",
    "source": "mundotek",
    "name": "kit fotográfico del Xiaomi 15 Ultra",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 99.0,
    "image": "imagenes/13-kit-fotogr-fico-del-xiaomi-15-ultra.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/kit15-300x251.webp",
    "url": "https://mundotek.com.ec/producto/kit-fotografico-del-xiaomi-15-ultra/",
    "badge": "Precio bajo"
  },
  {
    "id": "m4",
    "source": "mundotek",
    "name": "Realme C21Y Ram4GB/64GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 99.0,
    "image": "imagenes/14-realme-c21y-ram4gb-64gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/rmc21y-464gb-blu-9-1000x1000-1-768x768.jpg",
    "url": "https://mundotek.com.ec/producto/realme-c21y-ram4gb-64gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m5",
    "source": "mundotek",
    "name": "Realme C11 (2021) RAM 2GB/32GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 102.0,
    "image": "imagenes/15-realme-c11-2021-ram-2gb-32gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/07/Realme-C11-100x100.jpg",
    "url": "https://mundotek.com.ec/producto/realme-c11/",
    "badge": "Precio bajo"
  },
  {
    "id": "m6",
    "source": "mundotek",
    "name": "ZTE Blade A56 Pro RAM 4+8 /128GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 125.0,
    "image": "imagenes/16-zte-blade-a56-pro-ram-4-8-128gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/12/a56-pro-150x200.webp",
    "url": "https://mundotek.com.ec/producto/zte-blade-a56-pro-ram-48-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m7",
    "source": "mundotek",
    "name": "Infinix Hot 20i RAM 4+3 GB 128GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 129.0,
    "image": "imagenes/17-infinix-hot-20i-ram-4-3-gb-128gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/hot-20i-600x600.webp",
    "url": "https://mundotek.com.ec/producto/infinix-hot-20i-ram-43-gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m8",
    "source": "mundotek",
    "name": "Samsung A07 Ram 4GB- 128GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 135.0,
    "image": "imagenes/18-samsung-a07-ram-4gb--128gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/a07-600x600.webp",
    "url": "https://mundotek.com.ec/producto/samsung-a07-ram-4gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m9",
    "source": "mundotek",
    "name": "Tecno Spark Go 3 Ram4+4GB-128GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 135.0,
    "image": "imagenes/19-tecno-spark-go-3-ram4-4gb-128gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/tecno-spark-go-3-1200x1200.webp",
    "url": "https://mundotek.com.ec/producto/tecno-spark-go-3-ram44gb-64gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m10",
    "source": "mundotek",
    "name": "Honor Play 10 ram4+4 GB-128GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 135.0,
    "image": "imagenes/20-honor-play-10-ram4-4-gb-128gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/07/honor-play-10-600x600.jpg",
    "url": "https://mundotek.com.ec/producto/honor-play-10-ram44-gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m11",
    "source": "mundotek",
    "name": "Xiaomi Redmi A7 Pro Ram 4GB-128GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 135.0,
    "image": "imagenes/21-xiaomi-redmi-a7-pro-ram-4gb-128gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/xiaomi-redmi-a7-pro-600x600.webp",
    "url": "https://mundotek.com.ec/producto/xiaomi-redmi-a7-pro-ram-4gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m12",
    "source": "mundotek",
    "name": "LOGIC G1L GAMING PHONE+GAME PAD+BUDS RAM 4+10GB/ 128GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 139.0,
    "image": "imagenes/22-logic-g1l-gaming-phone-game-pad-buds-ram-4-10gb-128gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/08/logi-768x434.png",
    "url": "https://mundotek.com.ec/producto/logic-g1l-gaming-phonegame-padbuds-ram-410gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m13",
    "source": "mundotek",
    "name": "Infinix Smart 20 Ram 4 +4 GB -128GB-256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 139.0,
    "image": "imagenes/23-infinix-smart-20-ram-4-4-gb--128gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/infinix-smart-20-600x600.jpg",
    "url": "https://mundotek.com.ec/producto/infinix-smart-20-ram-4-4-gb-64gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m14",
    "source": "mundotek",
    "name": "MOTOROLA G06 Ram 4GB+4GB-256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 149.0,
    "image": "imagenes/24-motorola-g06-ram-4gb-4gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/g06-150x156.jpeg",
    "url": "https://mundotek.com.ec/producto/motorola-g06-ram-4gb4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m15",
    "source": "mundotek",
    "name": "TCL L10+",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 150.0,
    "image": "imagenes/25-tcl-l10.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/04/1062-100x100.jpg",
    "url": "https://mundotek.com.ec/producto/l10/",
    "badge": "Precio bajo"
  },
  {
    "id": "m16",
    "source": "mundotek",
    "name": "Honor X5c Plus Ram 4GB- 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 155.0,
    "image": "imagenes/26-honor-x5c-plus-ram-4gb--256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/x5plus-150x150.jpg",
    "url": "https://mundotek.com.ec/producto/honor-x5c-plus-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m17",
    "source": "mundotek",
    "name": "Telefono Tecno Spark 30C Ram 4GB/256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 159.0,
    "image": "imagenes/27-telefono-tecno-spark-30c-ram-4gb-256gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/11/spark30c-768x768.webp",
    "url": "https://mundotek.com.ec/producto/telefono-tecno-spark-30c-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m18",
    "source": "mundotek",
    "name": "OPPO A5 4G RAM 4GB-256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 165.0,
    "image": "imagenes/28-oppo-a5-4g-ram-4gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/a5-4g-600x600.png",
    "url": "https://mundotek.com.ec/producto/oppo-a5-4g-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m19",
    "source": "mundotek",
    "name": "Motorola moto g15 4G Ram 4+8/ 512GB-256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 169.0,
    "image": "imagenes/29-motorola-moto-g15-4g-ram-4-8-512gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/g15-768x768.png",
    "url": "https://mundotek.com.ec/producto/motorola-moto-g15-ram-48gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m20",
    "source": "mundotek",
    "name": "Tecno Spark 9 Pro",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 175.0,
    "image": "imagenes/30-tecno-spark-9-pro.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/11/Tecno-Spark-9-Pro-4-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/tecno-spark-9-pro/",
    "badge": "Precio bajo"
  },
  {
    "id": "m21",
    "source": "mundotek",
    "name": "Xiaomi Redmi 15c Ram 8gb / 256gb",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 179.0,
    "image": "imagenes/31-xiaomi-redmi-15c-ram-8gb-256gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/redmi15c-216x300.webp",
    "url": "https://mundotek.com.ec/producto/xiaomi-redmi-15c-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m22",
    "source": "mundotek",
    "name": "Honor X6c Ram 6GB-8GB/ 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 185.0,
    "image": "imagenes/32-honor-x6c-ram-6gb-8gb-256gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/06/x6c-768x768.webp",
    "url": "https://mundotek.com.ec/producto/honor-x6c-ram-6gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m23",
    "source": "mundotek",
    "name": "Motorola G17 Ram 4GB- 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 185.0,
    "image": "imagenes/33-motorola-g17-ram-4gb--256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/moto-g17-150x150.jpg",
    "url": "https://mundotek.com.ec/producto/motorola-g17-ram-4gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m24",
    "source": "mundotek",
    "name": "Realme Narzo 30 (5G)",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 195.0,
    "image": "imagenes/34-realme-narzo-30-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2021/11/719tm7l723L._SL1500_-100x100.jpg",
    "url": "https://mundotek.com.ec/producto/realme-narzo-30-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "m25",
    "source": "mundotek",
    "name": "Celular Oukitel G1 24 (6+18) Gb Ram /256 Gb color NARANJA",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 225.0,
    "image": "imagenes/35-celular-oukitel-g1-24-6-18-gb-ram-256-gb-color-naranja.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/g1-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/celular-oukitel-g1-24-618-gb-ram-256-gb-color-negro/",
    "badge": "Precio bajo"
  },
  {
    "id": "m26",
    "source": "mundotek",
    "name": "Honor X7d Ram 6+6GB/ 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 229.0,
    "image": "imagenes/36-honor-x7d-ram-6-6gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/10/honor-x7d-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/honor-x7d-ram-88gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m27",
    "source": "mundotek",
    "name": "MOTOROLA G56 5G 8GB+8GB-256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 229.0,
    "image": "imagenes/37-motorola-g56-5g-8gb-8gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/12/moto-56-600x600.png",
    "url": "https://mundotek.com.ec/producto/motorola-g56-5g-8gb8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m28",
    "source": "mundotek",
    "name": "Celular Zte Nubia Air 5G – Ram 8+12/256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 235.0,
    "image": "imagenes/38-celular-zte-nubia-air-5g-ram-8-12-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/celular-zte-nubia-air-5g-768x768.png",
    "url": "https://mundotek.com.ec/producto/celular-zte-nubia-air-5g-ram-812-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m29",
    "source": "mundotek",
    "name": "Honor 90 lite Ram 8GB/256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 239.0,
    "image": "imagenes/39-honor-90-lite-ram-8gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/honor-90-lite--768x768.jpg",
    "url": "https://mundotek.com.ec/producto/honor-90-lite-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m30",
    "source": "mundotek",
    "name": "Infinix Hot 60 pro plus 8+8GB 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 255.0,
    "image": "imagenes/40-infinix-hot-60-pro-plus-8-8gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/07/hot60pro-244x300.png",
    "url": "https://mundotek.com.ec/producto/infinix-hot-60-pro-plus-88gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m31",
    "source": "mundotek",
    "name": "SAMSUNG GALAXY A17 8GB -256GB Androir",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 259.0,
    "image": "imagenes/41-samsung-galaxy-a17-8gb--256gb-androir.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/sam-a17-4g-1200x1200.webp",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a17-4gb-128gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m32",
    "source": "mundotek",
    "name": "Xiaomi Mi 10 lite 128gb 6gb Ram 5G",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 269.0,
    "image": "imagenes/42-xiaomi-mi-10-lite-128gb-6gb-ram-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/01/1-15.svg",
    "url": "https://mundotek.com.ec/producto/xiaomi-mi-10-lite-128gb-6gb-ram-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "m33",
    "source": "mundotek",
    "name": "OPPO A5 5G Ram 8GB/ 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 269.0,
    "image": "imagenes/43-oppo-a5-5g-ram-8gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/oppoa5-300x294.png",
    "url": "https://mundotek.com.ec/producto/oppo-a5-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m34",
    "source": "mundotek",
    "name": "Oukitel WP53 4G 8+16GB 128GB 6.52″ Negro",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 276.0,
    "image": "imagenes/44-oukitel-wp53-4g-8-16gb-128gb-6-52-negro.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/112-oukitel-wp53-4g-8gb-128gb-150x150.jpg",
    "url": "https://mundotek.com.ec/producto/oukitel-wp53-4g-8gb-128gb-6-52-negro/",
    "badge": "Precio bajo"
  },
  {
    "id": "m35",
    "source": "mundotek",
    "name": "Redmi Note 15 Pro 4G Ram 8Gb-256Gb",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 299.0,
    "image": "imagenes/45-redmi-note-15-pro-4g-ram-8gb-256gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/xiaomi-redmi-note-15-pro-4g-600x600.webp",
    "url": "https://mundotek.com.ec/producto/redmi-note-15-4g-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m36",
    "source": "mundotek",
    "name": "Tecno camon 18 premier",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 315.0,
    "image": "imagenes/46-tecno-camon-18-premier.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/04/camon--100x100.jpg",
    "url": "https://mundotek.com.ec/producto/tecno-camon-18-premier/",
    "badge": "Precio bajo"
  },
  {
    "id": "m37",
    "source": "mundotek",
    "name": "Oppo A5 PRO (5G) Ram8GB/256GB IP69 SUMERGIBLE",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 319.0,
    "image": "imagenes/47-oppo-a5-pro-5g-ram8gb-256gb-ip69-sumergible.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/oppo-a5pro-300x300.webp",
    "url": "https://mundotek.com.ec/producto/oppo-a5-pro-5g-ram8gb-256gb-ip69-sumergible/",
    "badge": "Precio bajo"
  },
  {
    "id": "m38",
    "source": "mundotek",
    "name": "HONOR X8d Ram 8GB- 256GB/512GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 319.0,
    "image": "imagenes/48-honor-x8d-ram-8gb--256gb-512gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/honor-x8d-600x600.webp",
    "url": "https://mundotek.com.ec/producto/honor-x8d-ram-8gb-256gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m39",
    "source": "mundotek",
    "name": "Tecno Camón 50 pro Ram 8+8 GB/256GB+audifonos tipo diadema",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 339.0,
    "image": "imagenes/49-tecno-cam-n-50-pro-ram-8-8-gb-256gb-audifonos-tipo-diadema.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/camon-con-audifonos-600x600.png",
    "url": "https://mundotek.com.ec/producto/tecno-camon-50-pro-ram-88-gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m40",
    "source": "mundotek",
    "name": "Samsung Galaxy A36 5G Ram 8GB / 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 349.0,
    "image": "imagenes/50-samsung-galaxy-a36-5g-ram-8gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/a36-black-mtk-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a36-5g-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m41",
    "source": "mundotek",
    "name": "XIAOMI POCO F4 Ram 8GB/ 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 399.0,
    "image": "imagenes/51-xiaomi-poco-f4-ram-8gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/08/Nuevo-proyecto-11-1-1536x1536.png",
    "url": "https://mundotek.com.ec/producto/xiaomi-poco-f4-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m42",
    "source": "mundotek",
    "name": "Honor Magic8 Lite Ram 8GB/256GB-512GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 409.0,
    "image": "imagenes/52-honor-magic8-lite-ram-8gb-256gb-512gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/01/magi-8lite-600x600.webp",
    "url": "https://mundotek.com.ec/producto/honor-magic8-lite-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m43",
    "source": "mundotek",
    "name": "Infinix Note 60 Pro 5G RAM 8+8 GB/256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 419.0,
    "image": "imagenes/53-infinix-note-60-pro-5g-ram-8-8-gb-256gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/note60pro-600x600.webp",
    "url": "https://mundotek.com.ec/producto/infinix-note-60-pro-5g-ram-88-gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m44",
    "source": "mundotek",
    "name": "Motorola Edge 70 Fusion Ram 8GB-256GB +Buds motorola",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 419.0,
    "image": "imagenes/54-motorola-edge-70-fusion-ram-8gb-256gb-buds-motorola.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/70-fushion-600x600.png",
    "url": "https://mundotek.com.ec/producto/motorola-edge-70-fusion-ram-8gb-256gb-buds-motorola/",
    "badge": "Precio bajo"
  },
  {
    "id": "m45",
    "source": "mundotek",
    "name": "Samsung Galaxy A37 5G Ram 8GB- 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 419.0,
    "image": "imagenes/55-samsung-galaxy-a37-5g-ram-8gb--256gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/08/a37-150x150.webp",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a37-5g-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m46",
    "source": "mundotek",
    "name": "Samsung Galaxy A56 5G Ram 12GB/ 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 439.0,
    "image": "imagenes/56-samsung-galaxy-a56-5g-ram-12gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/a56-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a56-5g-ram-12gb-256gb-2/",
    "badge": "Precio bajo"
  },
  {
    "id": "m47",
    "source": "mundotek",
    "name": "Honor 600E Ram 8GB-256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 449.0,
    "image": "imagenes/57-honor-600e-ram-8gb-256gb.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/honor-e-150x225.webp",
    "url": "https://mundotek.com.ec/producto/honor-600e-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m48",
    "source": "mundotek",
    "name": "Redmi Note 15 Pro Plus 5G Ram 12GB- 512GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 489.0,
    "image": "imagenes/58-redmi-note-15-pro-plus-5g-ram-12gb--512gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/xiaomi-redmi-note15-pro-plus-150x113.png",
    "url": "https://mundotek.com.ec/producto/redmi-note-15-pro-plus-5g-ram-12gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m49",
    "source": "mundotek",
    "name": "Oppo Reno13F 5G Ram 12GB/ 512GB IP69",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 499.0,
    "image": "imagenes/59-oppo-reno13f-5g-ram-12gb-512gb-ip69.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/reno-13f-220x300.jpg",
    "url": "https://mundotek.com.ec/producto/reno13-f-5g-ram-12gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m50",
    "source": "mundotek",
    "name": "Oukitel WP62 5G RAM 24+24GB-512gbGB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 509.0,
    "image": "imagenes/60-oukitel-wp62-5g-ram-24-24gb-512gbgb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/wp60-600x600.jpg",
    "url": "https://mundotek.com.ec/producto/oukitel-wp62-5g-ram-24gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m51",
    "source": "mundotek",
    "name": "Oppo Reno14F Ram 12GB-512GB +AUDIFONOS",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 535.0,
    "image": "imagenes/61-oppo-reno14f-ram-12gb-512gb-audifonos.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/01/reno-150x185.webp",
    "url": "https://mundotek.com.ec/producto/oppo-reno14f-ram-12gb-512gb-audifonos/",
    "badge": "Precio bajo"
  },
  {
    "id": "m52",
    "source": "mundotek",
    "name": "Samsung Galaxy A57 Ram 8GB/12GB-256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 549.0,
    "image": "imagenes/62-samsung-galaxy-a57-ram-8gb-12gb-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/a57-600x600.png",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-a57-ram-8gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m53",
    "source": "mundotek",
    "name": "Xiaomi Poco x8 Pro Ram 12GB/ 512GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 569.0,
    "image": "imagenes/63-xiaomi-poco-x8-pro-ram-12gb-512gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/x8-pro-600x600.jpg",
    "url": "https://mundotek.com.ec/producto/xiaomi-poco-x8-pro-ram-12gb-512gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "m54",
    "source": "mundotek",
    "name": "IPHONE 11 PRO MAX OPEN BOX A 256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 579.0,
    "image": "imagenes/64-iphone-11-pro-max-open-box-a-256gb.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2022/09/11-pro-max-p-768x768.jpg",
    "url": "https://mundotek.com.ec/producto/iphone-11-pro-max-open-box/",
    "badge": "Precio bajo"
  },
  {
    "id": "m55",
    "source": "mundotek",
    "name": "Samsung Galaxy S25 FE Ram 8GB/ 256GB 5G",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 579.0,
    "image": "imagenes/65-samsung-galaxy-s25-fe-ram-8gb-256gb-5g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/12/samsung_galaxy_s25_fe-150x150.png",
    "url": "https://mundotek.com.ec/producto/samsung-galaxy-s25-fe-ram-8gb-256gb-5g/",
    "badge": "Precio bajo"
  },
  {
    "id": "m56",
    "source": "mundotek",
    "name": "Infinix GT 50 Pro HydroFlow y gatillos laterales Ram 12+12 GB-256GB",
    "specs": "Smartphone · Precio final · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 599.0,
    "image": "imagenes/66-infinix-gt-50-pro-hydroflow-y-gatillos-laterales-ram-12-12-g.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/07/infinix-gt-50-pro-launched-in-ph-c-150x94.jpg",
    "url": "https://mundotek.com.ec/producto/infinix-gt-50-pro-hydroflow-y-gatillos-laterales-ram-1212-gb-256gb/",
    "badge": "Precio bajo"
  },
  {
    "id": "t1",
    "source": "mundotek-tv",
    "name": "SMART TV INDURAMA TV 43TIKJ5UHD 43Pulgadas",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 309.0,
    "image": "imagenes/67-smart-tv-indurama-tv-43tikj5uhd-43pulgadas.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/02/tikhudhd-768x614.webp",
    "url": "https://mundotek.com.ec/producto/smart-tv-indurama-tv-43tikjuhd-43pulgadas/",
    "badge": "#1 más económico"
  },
  {
    "id": "t2",
    "source": "mundotek-tv",
    "name": "Televisor LG 43pulgadas UHD AI 43UA75 4K Smart TV 2025",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 325.0,
    "image": "imagenes/68-televisor-lg-43pulgadas-uhd-ai-43ua75-4k-smart-tv-2025.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/10/43ua75-768x576.webp",
    "url": "https://mundotek.com.ec/producto/televisor-lg-43pulgadas-uhd-ai-43ua75-4k-smart-tv-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t3",
    "source": "mundotek-tv",
    "name": "TV Innova IN LED 50UHD GTV 50″ GOOGLE TV",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 345.0,
    "image": "imagenes/69-tv-innova-in-led-50uhd-gtv-50-google-tv.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/50uhd-150x150.png",
    "url": "https://mundotek.com.ec/producto/tv-innova-in-led-50uhd-gtv-50-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t4",
    "source": "mundotek-tv",
    "name": "Smart tv Tcl 50S5K 50 » fhd qled android 14 google tv panel hva QLED",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 349.0,
    "image": "imagenes/70-smart-tv-tcl-50s5k-50-fhd-qled-android-14-google-tv-panel-hv.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/s5k-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-tcl-50s5k-50-fhd-qled-android-14-google-tv-panel-hva-qled/",
    "badge": "Precio bajo"
  },
  {
    "id": "t5",
    "source": "mundotek-tv",
    "name": "TCL P755 4K UHD Google TV 50PULGADAS",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 369.0,
    "image": "imagenes/71-tcl-p755-4k-uhd-google-tv-50pulgadas.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/03/tcl-p755-1536x1152.png",
    "url": "https://mundotek.com.ec/producto/tcl-p755-4k-uhd-google-tv-50pulgadas/",
    "badge": "Precio bajo"
  },
  {
    "id": "t6",
    "source": "mundotek-tv",
    "name": "TV RIVIERA QLED 4K -GLT50TPQ10 50″ GOOGLE TV",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 369.0,
    "image": "imagenes/72-tv-riviera-qled-4k--glt50tpq10-50-google-tv.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/rled-glt50tpq10-300x300.png",
    "url": "https://mundotek.com.ec/producto/tv-riviera-qled-4k-glt50tpq10-50%e2%80%b3-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t7",
    "source": "mundotek-tv",
    "name": "Televisor inteligente Crystal UHD DU7000 4K de 50” con sistema operativo Tizen",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 369.0,
    "image": "imagenes/73-televisor-inteligente-crystal-uhd-du7000-4k-de-50-con-sistem.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/du7000-mtk-768x768.webp",
    "url": "https://mundotek.com.ec/producto/televisor-inteligente-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen-oferta-de-verano/",
    "badge": "Precio bajo"
  },
  {
    "id": "t8",
    "source": "mundotek-tv",
    "name": "Tv Indurama LED 4K50 Pulgadas (50TIKGF2GUHD Google Tv)",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 379.0,
    "image": "imagenes/74-tv-indurama-led-4k50-pulgadas-50tikgf2guhd-google-tv.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/10/d_nq_np_783527-mec53271187298_012023-o-300x199.webp",
    "url": "https://mundotek.com.ec/producto/tv-indurama-qled-50-pulgadas-50tikgf2guhd-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t9",
    "source": "mundotek-tv",
    "name": "Smart tv Innova IN-LED-55UHD-GTV-MP 55 » 4k uhd led",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 379.0,
    "image": "imagenes/75-smart-tv-innova-in-led-55uhd-gtv-mp-55-4k-uhd-led.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/12/in-led55mtk-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-innova-in-led-55uhd-gtv-mp-55-4k-uhd-led/",
    "badge": "Precio bajo"
  },
  {
    "id": "t10",
    "source": "mundotek-tv",
    "name": "Smart tv Rca LED55RCA684GT 55 » 4k uhd led android google tv",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 399.0,
    "image": "imagenes/76-smart-tv-rca-led55rca684gt-55-4k-uhd-led-android-google-tv.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/07/rca684gt-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-rca-led55rca684gt-55-4k-uhd-led-android-google-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t11",
    "source": "mundotek-tv",
    "name": "Smart tv Riviera RLED-GLT55PX9 55 » 4k uhd led android google tv color negro 2025",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 399.0,
    "image": "imagenes/77-smart-tv-riviera-rled-glt55px9-55-4k-uhd-led-android-google-.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/google-tv-glt55px9-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-rled-glt55tpx9-55-4k-uhd-led-android-google-tv-color-negro/",
    "badge": "Precio bajo"
  },
  {
    "id": "t12",
    "source": "mundotek-tv",
    "name": "Televisor LG UHD AI 50UA7500 4K Smart TV",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 409.0,
    "image": "imagenes/78-televisor-lg-uhd-ai-50ua7500-4k-smart-tv.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/50ua7500-150x100.jpeg",
    "url": "https://mundotek.com.ec/producto/televisor-lg-uhd-ai-50ua7500-4k-smart-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t13",
    "source": "mundotek-tv",
    "name": "LG UHD 50» UR7300 4K Smart TV con ThinQ AI , 4K Procesador Inteligente",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 419.0,
    "image": "imagenes/79-lg-uhd-50-ur7300-4k-smart-tv-con-thinq-ai-4k-procesador-inte.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/07/image-1-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/lg-uhd-50-ur7300-4k-smart-tv-con-thinq-ai-4k-procesador-inteligente/",
    "badge": "Precio bajo"
  },
  {
    "id": "t14",
    "source": "mundotek-tv",
    "name": "Tv Hisense 55″ LED 4K Smart VIDAA 55A6H",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 419.0,
    "image": "imagenes/80-tv-hisense-55-led-4k-smart-vidaa-55a6h.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/05/tv-hisense-55-55a6h-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-tv-hisense-55%e2%80%b3-led-4k-smart-vidaa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t15",
    "source": "mundotek-tv",
    "name": "Televisor Hisense 55Q6QV 55 » 4k uhd QLED Vidaa",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 419.0,
    "image": "imagenes/81-televisor-hisense-55q6qv-55-4k-uhd-qled-vidaa.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/55q6qv-150x150.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-hisense-55q6qv-55-4k-uhd-qled-vidaa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t16",
    "source": "mundotek-tv",
    "name": "Televisor 55Pulgadas TCL P6K 4K UHD",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 429.0,
    "image": "imagenes/82-televisor-55pulgadas-tcl-p6k-4k-uhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/tv-tcl-55-55p6k-150x150.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-55pulgadas-tcl-p6k-4k-uhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t17",
    "source": "mundotek-tv",
    "name": "Televisor Riviera QLED 55″ RLED-GLT55TPQ10",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 429.0,
    "image": "imagenes/83-televisor-riviera-qled-55-rled-glt55tpq10.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/11/rled-glt55tpq10-768x768.webp",
    "url": "https://mundotek.com.ec/producto/televisor-riviera-qled-55-rled-glt55tpq10/",
    "badge": "Precio bajo"
  },
  {
    "id": "t18",
    "source": "mundotek-tv",
    "name": "Televisor Motorola 55MGFUHD Google 4K Tv 55″",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 439.0,
    "image": "imagenes/84-televisor-motorola-55mgfuhd-google-4k-tv-55.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2024/10/mtk-tmkuhd-300x300.png",
    "url": "https://mundotek.com.ec/producto/televisor-motorola-55tmkuhd-google-tv-55/",
    "badge": "Precio bajo"
  },
  {
    "id": "t19",
    "source": "mundotek-tv",
    "name": "Televisor PHILIPS QLED 55″ Pulgadas UHD 4K – Google TV – Q55gfu",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 439.0,
    "image": "imagenes/85-televisor-philips-qled-55-pulgadas-uhd-4k-google-tv-q55gfu.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/55gfu-600x600.png",
    "url": "https://mundotek.com.ec/producto/televisor-philips-qled-55%e2%80%b3-pulgadas-uhd-4k-google-tv-q55gfu/",
    "badge": "Precio bajo"
  },
  {
    "id": "t20",
    "source": "mundotek-tv",
    "name": "Televisor inteligente Crystal UHD DU7000 4K de 50” con sistema operativo Tizen",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 459.0,
    "image": "imagenes/86-televisor-inteligente-crystal-uhd-du7000-4k-de-50-con-sistem.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/01/du7000-mtk-768x768.webp",
    "url": "https://mundotek.com.ec/producto/televisor-inteligente-crystal-uhd-du7000-4k-de-50-con-sistema-operativo-tizen-2024-copia/",
    "badge": "Precio bajo"
  },
  {
    "id": "t21",
    "source": "mundotek-tv",
    "name": "Televisor Qled TCL T6C 55 PULGADAS",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 489.0,
    "image": "imagenes/87-televisor-qled-tcl-t6c-55-pulgadas.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/qled-tcl-t6c-768x768.webp",
    "url": "https://mundotek.com.ec/producto/televisor-qled-tcl-t6c-55-pulgadas/",
    "badge": "Precio bajo"
  },
  {
    "id": "t22",
    "source": "mundotek-tv",
    "name": "Samsung 50 pulgadas 50Q7FAA Series 4K Vision AI Smart TV",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 489.0,
    "image": "imagenes/88-samsung-50-pulgadas-50q7faa-series-4k-vision-ai-smart-tv.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/q7faa-50.avif",
    "url": "https://mundotek.com.ec/producto/samsung-50-pulgadas-50q7faa-series-4k-vision-ai-smart-tv/",
    "badge": "Precio bajo"
  },
  {
    "id": "t23",
    "source": "mundotek-tv",
    "name": "TV 55″ Crystal UHD 4K 55U8000 Tizen OS Smart TV (2026)",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 499.0,
    "image": "imagenes/89-tv-55-crystal-uhd-4k-55u8000-tizen-os-smart-tv-2026.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/ue65u8000-300x300.png",
    "url": "https://mundotek.com.ec/producto/tv-55-crystal-uhd-4k-u8000-tizen-os-smart-tv-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t24",
    "source": "mundotek-tv",
    "name": "TELEVISOR INNOVA IN-TVLED-65GUHD-MP GOOGLE TV 65″",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 519.0,
    "image": "imagenes/90-televisor-innova-in-tvled-65guhd-mp-google-tv-65.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/04/tv65.avif",
    "url": "https://mundotek.com.ec/producto/televisor-innova-in-tvled-65guhd-mp-google-tv-65/",
    "badge": "Precio bajo"
  },
  {
    "id": "t25",
    "source": "mundotek-tv",
    "name": "Televisor Philips Led 65GFS-FISDB Google Tv 65″",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 525.0,
    "image": "imagenes/91-televisor-philips-led-65gfs-fisdb-google-tv-65.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/03/philips-65-gfs-fisdb-600x600.png",
    "url": "https://mundotek.com.ec/producto/televisor-philips-led-65gfs-fisdb-google-tv-65/",
    "badge": "Precio bajo"
  },
  {
    "id": "t26",
    "source": "mundotek-tv",
    "name": "55″ LG UHD AI 4K Smart TV 55ua7300 2025",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 530.0,
    "image": "imagenes/92-55-lg-uhd-ai-4k-smart-tv-55ua7300-2025.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/10/65ua73-300x300.webp",
    "url": "https://mundotek.com.ec/producto/55-lg-uhd-ai-4k-smart-tv-55ua7300-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t27",
    "source": "mundotek-tv",
    "name": "Televisor Samsung 55″ Mini LED UHD UN55M70HAGXPE",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 539.0,
    "image": "imagenes/93-televisor-samsung-55-mini-led-uhd-un55m70hagxpe.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/nini-led-sam-600x600.webp",
    "url": "https://mundotek.com.ec/producto/televisor-samsung-55-mini-led-uhd-un55m70hagxpe/",
    "badge": "Precio bajo"
  },
  {
    "id": "t28",
    "source": "mundotek-tv",
    "name": "Televisor LG 60″ LED 4K UHD 60UA8500PSA",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 549.0,
    "image": "imagenes/94-televisor-lg-60-led-4k-uhd-60ua8500psa.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/05/60ua85-600x600.webp",
    "url": "https://mundotek.com.ec/producto/televisor-lg-60-led-4k-uhd-60ua8500psa/",
    "badge": "Precio bajo"
  },
  {
    "id": "t29",
    "source": "mundotek-tv",
    "name": "Pantalla LG NanoCell 55» NANO80TSA 4K SMART TV con ThinQ AI",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 555.0,
    "image": "imagenes/95-pantalla-lg-nanocell-55-nano80tsa-4k-smart-tv-con-thinq-ai.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2023/09/55nano77-768x768.webp",
    "url": "https://mundotek.com.ec/producto/pantalla-lg-nanocell-55-nano77-4k-smart-tv-con-thinq-ai/",
    "badge": "Precio bajo"
  },
  {
    "id": "t30",
    "source": "mundotek-tv",
    "name": "Smart tv Riviera GLT65PX9 65 » 4k uhd led android google tv sin borde mando de voz 2025",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 569.0,
    "image": "imagenes/96-smart-tv-riviera-glt65px9-65-4k-uhd-led-android-google-tv-si.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/tv-glt65px9-300x300.jpg",
    "url": "https://mundotek.com.ec/producto/smart-tv-riviera-glt65px9-65-4k-uhd-led-android-google-tv-sin-borde-mando-de-voz-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t31",
    "source": "mundotek-tv",
    "name": "Televisor Motorola 65″ LED 4K UHD 65MNUHD",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 569.0,
    "image": "imagenes/97-televisor-motorola-65-led-4k-uhd-65mnuhd.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/65mnuhd-600x600.webp",
    "url": "https://mundotek.com.ec/producto/televisor-motorola-65-led-4k-uhd-65mnuhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t32",
    "source": "mundotek-tv",
    "name": "Televisores Hisense 65Q6QV 65″ 4k uhd qled vidaa color",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 579.0,
    "image": "imagenes/98-televisores-hisense-65q6qv-65-4k-uhd-qled-vidaa-color.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/02/65q6qv-150x150.jpg",
    "url": "https://mundotek.com.ec/producto/televisores-hisense-65q6qv-65-4k-uhd-qled-vidaa-color/",
    "badge": "Precio bajo"
  },
  {
    "id": "t33",
    "source": "mundotek-tv",
    "name": "Televisor 65″ INDURAMA UHD Google Tv TIKGF2GUHD",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 580.0,
    "image": "imagenes/99-televisor-65-indurama-uhd-google-tv-tikgf2guhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/05/65-tikgf2gudh-4k-google-tv-768x768.png",
    "url": "https://mundotek.com.ec/producto/televisor-65-indurama-uhd-google-tv-tikgf2guhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t34",
    "source": "mundotek-tv",
    "name": "Tv Samsung 55″ QLED Q7FAA 4K Vision AI Smart TV (2025)",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 589.0,
    "image": "imagenes/100-tv-samsung-55-qled-q7faa-4k-vision-ai-smart-tv-2025.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/09/tv-300x300.webp",
    "url": "https://mundotek.com.ec/producto/55-qled-q7f-4k-samsung-vision-ai-smart-tv-2025/",
    "badge": "Precio bajo"
  },
  {
    "id": "t35",
    "source": "mundotek-tv",
    "name": "Televisor 65Pulgadas TCL P6K 4K UHD",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 599.0,
    "image": "imagenes/101-televisor-65pulgadas-tcl-p6k-4k-uhd.jpg",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2025/04/p6k-150x150.jpg",
    "url": "https://mundotek.com.ec/producto/televisor-65pulgadas-tcl-p6k-4k-uhd/",
    "badge": "Precio bajo"
  },
  {
    "id": "t36",
    "source": "mundotek-tv",
    "name": "TV Hisense Hi-QLED MiniLED 55″ 4K 55U6ESG Google TV 2026",
    "specs": "Smart TV · Imagen de alta definición · Consulta disponibilidad · Cotización por WhatsApp",
    "price": 599.0,
    "image": "imagenes/102-tv-hisense-hi-qled-miniled-55-4k-55u6esg-google-tv-2026.webp",
    "image_remote": "https://mundotek.com.ec/wp-content/uploads/2026/06/50u6esg-600x600.webp",
    "url": "https://mundotek.com.ec/producto/tv-hisense-hi-qled-miniled-55-4k-55u6esg-google-tv-2026/",
    "badge": "Precio bajo"
  }
];
